librariapp/config/routes.rb
Rails.application.routes.draw do
  resources :sale_details

  resources :sales

  resources :clients do
  collection do
    post :find
    get :find
    end
  end

  resources :products do
    collection do
      post :find
      get :find
    end
  end

  resources :providers

end

librariapp/app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :client, :autosave => true
	has_many :saleDetails, :autosave => true
	accepts_nested_attributes_for :saleDetails
end

librariapp/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    # asociar un nuevo cliente
    @sale.client = Client.new

    #@sale.saleDetails << SaleDetail.new(:product_id => 1, :preciounitario=>100, :cantidad => 1, :importe => 100)
    #@sale.saleDetails << SaleDetail.new(:product_id => 4, :preciounitario=>234, :cantidad => 2, :importe => 468)

  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    client = Client.new(client_params)
    @sale.fecha = Time.new
    #al recibir los datos, comprobar si existe el cliente, entonces se pueden actualizar sus datos

    # si no existe el cliente, registrar un nuevo
    if @sale.client_id.nil?
       @sale.client = client
    else
      @sale.client.nombre = client.nombre ##si el cliente ya existe, se actualiza al nuevo valor recibido
      @sale.client.direccion = client.direccion
      @sale.client.telefono = client.telefono
      @sale.client.email = client.email
      @sale.client.facebook = client.facebook
      @sale.client.linkedin = client.linkedin
    end

  #  puts "Datos recibidos de la nueva venta"
  #  @sale.client.nombre = client.nombre ##si el cliente ya existe, se actualiza al nuevo valor recibido
  #  puts "cliente>> " + @sale.client_id.to_s + @sale.client.nombre.to_s
  #  puts "Productos recibidos: " 
    
    
  #  @sale.saleDetails.each do |item|
  #   #params[:saledetails].each do |item|
  #     puts "id: " + item.product_id.to_s + ", p. u: " + item.preciounitario.to_s + ", cantidad: " + item.cantidad.to_s + ", importe: " + item.importe.to_s
  #  end 

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:client_id, :fecha, :importe)
    end

    def client_params
      params.require(:client).permit(:nombre, :direccion, :telefono, :email, :facebook, :linkedin)
    end

    # def details_params
     #   params.require(:saleDetails_attributes).permit({:product_id => []}, {:preciounitario => []}, {:cantidad => []}, {:importe=> []})
     # end
end

librariapp/app/helpers/sales_helper.rb
module SalesHelper
end

librariapp/app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="datosClient">
  <fieldset>
  <legend>Datos del cliente</legend>
  <input type="text" name="client_id" id="client_id" placeholder="numero de registro"/> <br>
     <%= fields_for @sale.client do |c| %>
       <%= c.hidden_field :id %>
        <%= c.text_field :nombre, :placeholder => "Nombre del cliente" %> <br>
        <%= c.text_field :direccion, :placeholder => "Domicilio" %><br>
        <%= c.text_field :email, :placeholder => "Email del cliente" %> <br>
        <%= c.text_field :telefono, :placeholder => "Teléfono del cliente" %><br>
         <%= c.text_field :facebook, :placeholder => "Facebook del cliente" %> <br>
        <%= c.text_field :linkedin, :placeholder => "Linkedin del cliente" %>
        
    <% end %>
  </fieldset>
</div>
  

<div id="detallesVentaContainer">
    <di id="agregarProductoContainer">
      <input type="text" name="clavelibro" id="clavelibro" placeholder="Clave del libro"/>
      <input type="number" name="cantidadlibro" id="cantidadlibro" placeholder="Cantidad" value="1">
    </div>

     <table id="detallesVentaTable" cellspacing="0">
    <thead>
      <th>Clave</th>
      <th>Descripción</th>
      <th>P. Unidad</th>
      <th>Cantidad</th>
      <th>Importe</th>
    </thead>
    <tbody>
      <% @sale.saleDetails.each do |item| %>
        <%= f.fields_for :saleDetails, item do |d| %>
          <tr>
            <td><%= d.text_field :product_id, :class =>"idLibroVender" %></td>
            <td><input type="text" id="nombreProducto" value=""></td>
            <td><%= d.text_field :preciounitario %></td>
            <td><%= d.text_field :cantidad, :class =>"cantidadVender" %></td>
            <td><%= d.text_field :importe, :class =>"importeProducto" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <th colspan="2">Total de artículos:</th>
      <th id="totalArts">0</th>
      <th>Importe total:</th>
      <th id="importeTotalVenta">0</th>
    </tfoot>
  </table>
</div>

   <div class="form-actions">
    <%#= f.submit %>
    <button name="guardarVenta" id="guardarVenta" type="button" class="btn btn-primary">Registrar venta</button>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), sales_path, :class => 'btn' %>
  </div>
  </div>
<% end %>

librariapp/app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

librariapp/app/views/sales/index.html.erb
<h1>Listing sales</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Fecha</th>
      <th>Importe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.client_id %></td>
        <td><%= sale.fecha %></td>
        <td><%= sale.importe %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

librariapp/app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

librariapp/app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="datosClient">
  <fieldset>
  <legend>Datos del cliente</legend>
  <input type="text" name="client_id" id="client_id" placeholder="numero de registro"/> <br>

     <%= fields_for @sale.client do |c| %>
       <%= c.hidden_field :id %>
        <%= c.text_field :nombre, :placeholder => "Nombre del cliente" %> <br>
        <%= c.text_field :direccion, :placeholder => "Domicilio" %><br>
        <%= c.text_field :email, :placeholder => "Email del cliente" %> <br>
        <%= c.text_field :telefono, :placeholder => "Teléfono del cliente" %><br>
         <%= c.text_field :facebook, :placeholder => "Facebook del cliente" %> <br>
        <%= c.text_field :linkedin, :placeholder => "Linkedin del cliente" %>
        
    <% end %>
  </fieldset>
</div>
  

<div id="detallesVentaContainer">
    <di id="agregarProductoContainer">
      <input type="text" name="clavelibro" id="clavelibro" placeholder="Clave del libro"/>
      <input type="number" name="cantidadlibro" id="cantidadlibro" placeholder="Cantidad" value="1">
    </div>

     <table id="detallesVentaTable" cellspacing="0">
    <thead>
      <th>Clave</th>
      <th>Descripción</th>
      <th>P. Unidad</th>
      <th>Cantidad</th>
      <th>Importe</th>
    </thead>
    <tbody>
      <% @sale.saleDetails.each do |item| %>
        <%= f.fields_for :saleDetails, item do |d| %>
          <tr>
            <td><%= d.text_field :product_id, :class =>"idLibroVender" %></td>
            <td><input type="text" id="nombreProducto" value=""></td>
            <td><%= d.text_field :preciounitario %></td>
            <td><%= d.text_field :cantidad, :class =>"cantidadVender" %></td>
            <td><%= d.text_field :importe, :class =>"importeProducto" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <th colspan="2">Total de artículos:</th>
      <th id="totalArts">0</th>
      <th>Importe total:</th>
      <th id="importeTotalVenta">0</th>
    </tfoot>
  </table>
</div>
 <%end%>