librariapp/config/routes.rb
Rails.application.routes.draw do
  resources :sale_details

  resources :sales

  resources :clients do
  collection do
    post :find
    get :find
    end
  end

  resources :products do
    collection do
      post :find
      get :find
    end
  end

  resources :providers

end

librariapp/app/models/provider.rb
class Provider < ActiveRecord::Base
end

librariapp/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:Razonsocial, :telefono, :direccion, :fecha, :email, :rfc)
    end
end

librariapp/app/helpers/providers_helper.rb
module ProvidersHelper
end

librariapp/app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Razonsocial %><br>
    <%= f.text_field :Razonsocial %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :rfc %><br>
    <%= f.text_field :rfc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

librariapp/app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

librariapp/app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <thead>
    <tr>
      <th>Razonsocial</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Fecha</th>
      <th>Email</th>
      <th>Rfc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.Razonsocial %></td>
        <td><%= provider.telefono %></td>
        <td><%= provider.direccion %></td>
        <td><%= provider.fecha %></td>
        <td><%= provider.email %></td>
        <td><%= provider.rfc %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

librariapp/app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

librariapp/app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Razonsocial:</strong>
  <%= @provider.Razonsocial %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @provider.telefono %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @provider.direccion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @provider.fecha %>
</p>

<p>
  <strong>Email:</strong>
  <%= @provider.email %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @provider.rfc %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>